### PR TITLE
feat: add the curl command to perform health check

### LINKED ISSUE #57: Add the curl command to perform health check

### PR DESCRIPTION
**Pull request by hwzhuhao**
Add the curl command to perform health checks for the dify-sandbox service in the dify's docker-compose.yaml file.

close #57

### CODE REVIEW

**Comment by hwzhuhao** [comment]
@Yeuoly please help me to review, thanks. The purpose of this is to enable health checks for the sandbox within the docker-compose.yaml or Helm charts. This would ensure that the sandbox is functioning properly and allows for a more robust and reliable deployment.

**Comment by Yeuoly** [comment]
pls rebase to main branch, I will approve it later.

**Comment by hwzhuhao** [comment]
@Yeuoly I have resolved the conflict. pls help me to review it again.

**Review by Yeuoly — APPROVED** [review]
lgtm

**Pull request merged**
